recurly/recurly-js

- package.json
- Fixes build
- Due to mocha-phantomjs incompatibility with our browser-based mocha
- Follow-up: update browser mocha
> Locks mocha-phantomjs to 3.5.2

- lib/util/parse-card.js
- test/unit/validate.test.js
- instead of parseCard returning false, it returns an empty string that cardNumber can parse
- Fixes #161
/cc @bhelx
> Fixes validate.cardNumber throwing on falsey values

- lib/recurly/pricing/attach.js
- lib/recurly/pricing/index.js
- Calls to pricing.coupon will no longer abort if the coupon code hasn't changed. This accomodates plan changes that may nullify a coupon that may wok on other plans
- Corrects not-found error code check in pricing.coupon
- pricing.plan calls will now make pricing.coupon calls if a coupon is set on the instance
- Fixes #175
> Fixes issue with pricing coupon and plan mismatches

- lib/recurly/pricing/attach.js
- This places the detachment method on the true instance, instead of storing on the attach method prototype
- When multiple pricing instances from the same `Pricing` prototype definition are attached to separate forms, the pricing `attach` method would look for detach on the `attach` prototype. This should instead reside strictly on the instance.
> Fixes issue where Pricing detachment fails on multiple instances

- lib/recurly/validate.js
- test/unit/validate.test.js
- It is common to want to detect a card's type before the entire card is input.
- Adds a second boolean parameter to the method.
- Passing true to the `partial` parameter instructs the method to ignore the card length detections and rely solely on pattern detection.
> Allows cardType to run detections on partial numbers

- lib/recurly/pricing/calculations.js
- Instead of using a rounding method prone to floating point math issues, this uses a coercion using exp notation
- Tests provided in #198
> Fixes issue with tax rounding

- lib/recurly.js
- lib/recurly/token.js
- test/unit/configure.test.js
- test/unit/token.test.js
Hello,
At work, I needed additional field validations on client side so I created this PR :)
This PR gives us(merchants) a control about which additional required fields to be validated on browser.
**Changes:**
Change token.validate() to validate 'cvv' (only when cvv exists) and merchant pre-defined required fields as well.
**How it works:**
Merchant setups additional required fields with recurly.configure().
```javascript
recurly.configure({
'publicKey': 'abcd1234-key',
'extraRequiredFields': ['cvv', 'postal_code', 'country']
});
```
When user submits form, token.validate() now checks if those required fields exist or not, too, through token().
(Also, it checks 'cvv' only when cvv has a value.)
**Why this is helpful?**
We use recurly.js at work and we wanted to check if "postal code", …
> Add optional field validation

- lib/recurly.js
- XDRs are known to abort if too many are sent simultaneously
- This allows sends to execute asynchronously from their setup and space apart more.
- This will fix intermittent IE9 test failures
- See note on https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest
> Fixes an issue where XDRs aborted unpredictably

- lib/recurly/pricing/calculations.js
- test/server/fixtures/plans/basic/coupons/coop-pct.json
- test/server/fixtures/plans/basic/coupons/coop-single-use.json
- test/server/fixtures/plans/intermediate/coupons/coop-pct.json
- test/server/fixtures/plans/intermediate/coupons/coop.json
- test/unit/coupon.test.js
- test/unit/pricing.test.js
https://github.com/recurly/recurly-js/issues/167
When calculating discount for coupons, check single_use property before applying discount to next invoice estimate.
> update discount calculations to respect single_use coupons

- lib/recurly/token.js
- test/validate.test.js
When validating input values, check if cvv is present in required fields before skipping an empty value.
> Check if cvv is required before ignoring empty value

- lib/recurly.js
- lib/recurly/bus.js
The bus.reset() call was removing the event listener -- this patch just reconnects it.
Please note my environment isn't set up to run the test suite on this, but it works well for my use case.
> Reconnects bus after reset (fixes field integrity check)

- karma.conf.js
- lib/recurly/pricing/attach.js
- lib/recurly/pricing/index.js
- test/pricing/pricing.test.js
- Still sets the not found coupon, consistent with current behavior
- Fixes #262 
```js
let pricing = recurly.Pricing();
pricing.attach(form);
pricing.on('error.coupon', function (err) {
// err.code === 'not-found'
});
```
```js
let pricing = recurly.Pricing()
.plan('basic')
.coupon('invalid')
.catch(function (err) {
// err.code === 'not-found'
});
```
- Adds the 'unset.coupon' event to pricing instances
- Adds debugger to default karma runner
> Emits a pricing error when a coupon is not found

- README.md
- lib/recurly.js
- lib/recurly/fraud.js
- test/pricing/attachment.test.js
- test/support/helpers.js
- test/token.test.js
- 🍺 
- Also removes a `setTimeout` from the fraud tests, ~20% test speed increase
> Enables CORS by default

- lib/recurly/validate.js
- test/validate.test.js
- `parseInt` was coercing in a pattern inconsistent with the tokenization API
- Fixes #277
> Fixes expiry validation for invalid input

- lib/util/dom.js
- If a merchant uses a select input with no options in a pricing attachment (see example below), the `valueGet` function would blow up as described in #220.
- Fixes #220
```html
<form>
<select data-recurly="plan">
</select>
</form>
```
```js
let pricing = recurly.Pricing();
pricing.attach(document.querySelector('form'));
// ... retrieve plans asynchronously and add options to the plan select input
```
> Adds safety check to dom value get method

- lib/recurly/hosted-field.js
- Finds labels paired to containers via for-id match
- Sends `hostedField:${type}:focus!` event when label is clicked/tapped
- This will not work with mobile Safari due to strict focus event constraints. See [this][so]
- Fixes #240
- Fixes #271
[so]: http://stackoverflow.com/questions/12204571/mobile-safari-javascript-focus-method-on-inputfield-only-works-with-click#answer-16601288
> Allows a label tag paired to a field container to defer focus to the field

- lib/recurly/pricing/attachment.js
- Addons were being set before plans might be available on pricing.
- Attachment assumes a `PricingPromise` at all times during update. This ensures it has one.
> Fixes bug with pricing attachment of addons

- lib/recurly/hosted-field.js
- test/server/fixtures/field.html.ejs
- test/server/index.js
- This will let us cache those responses more aggressively
> Sends initial field config over hash instead of query

- lib/recurly/pricing/attachment.js
- lib/recurly/pricing/calculations.js
- lib/recurly/pricing/index.js
- lib/recurly/pricing/promise.js
- test/pricing/attachment.test.js
- test/pricing/pricing.test.js
- test/support/fixtures.js
- Adds pricing class support for shipping address
- Adds attachment procedure for shipping address
- Establishes that shipping address holds precedence for billing address in tax calculations
```js
let pricing = recurly.Pricing();
pricing.plan('basic', { quantity: 1 })
.address({
country: 'DE'
})
.shippingAddress({
country: 'US',
postal_code: '94129',
vat_number: ''
})
.done(function (price) {
// will calculate taxes based on shipping address and not (billing) address
});
```
```html
<input data-recurly="shipping_address.country" type="text">
<input data-recurly="shipping_address.postal_code" type="text">
```
> Adds support for shipping address

- lib/recurly/hosted-field.js
- lib/recurly/hosted-fields.js
- Fixes issue where external configuration assignments could undermine integrity checks
> Ensures configuration objects are not externally mutable

- lib/recurly/hosted-field.js
- lib/recurly/hosted-fields.js
- package.json
This PR does 2 things to add mobile tabbing between hosted fields support.
1) Adds a "hidden" input before the iFrame. iOS Safari at least doesn't tab into the iframe like most desktop browsers do. The hidden input just transfers the focus from itself to the hosted field inside.
2) Adds support for hostedField:tab:previous and hostedField:tab:next events. These events just grab all [data-recurly] elements (either actual input fields or a div containing a hosted field), and then transfer focus to whichever one is previous or next.
> Add support for tabbing in a Mobile browser.

- lib/recurly.js
- test/server/fixtures/token/index.js
- test/token.test.js
We've seen some errors where the Recurly API must have responded with invalid JSON, but we haven't been able to see it live in order to see what the responseText actually is, so it'd would be helpful to include that in the error message.
> Include the responseText when json is invalid

- lib/recurly/apple-pay.js
When sending Apple Pay payment data for a token, include the name and address fields. These are required to later build a valid billing info so that the customer can be billed successfully.
cc: @chrissrogers
> Also send name, address, etc fields for apple pay token creation

- index.js
- modules which depend on recurly.js need this to be a proper relative path.
> Fixes dependent module resolution to main

- lib/recurly/paypal/index.js
- Callbacks were improperly registered with the deprecated PayPal invocation
> Fixes issue with new PayPal API usage of deprecated method

- lib/recurly/hosted-field.js
- Defers click events on the container to focus on the hosted field
- Allows containers with padding to defer clicks within the padding to focus on the hosted field
> Adds field container click event deference

- lib/errors.js
- lib/recurly/paypal/strategy/braintree.js
- For when Braintree is misconfigured within Recurly [here](https://github.com/recurly/recurly-js/blob/master/lib/recurly/paypal/strategy/braintree.js#L100)
cc @karentobo
> Adds a missing error type

- Makefile
- When using a proxy server during local development, it will be terminating tls connections instead of the app server
> Adds support for starting an http server

- .travis.yml
- karma.ci.conf.js
- lib/recurly/apple-pay.js
- test/apple-pay.test.js
If the merchant doesn't supply a form for the user to specify name and address data, attempt to use data present in Apple Pay contact data.
**Testing notes**
> use Apple Pay contact data when form name and address are not supplied

- lib/recurly/apple-pay.js
- test/apple-pay.test.js
We recently added the ability to use the Apple Pay contact data for name/address but the code still has a validation for passing in a form, which isn't required now. This update removes that requirement.
> Don’t require form for Apple Pay

- lib/recurly/bus.js
- iOS 11 CI tests have not proven reliable
- Field window.postMessage is not always available. This attempts to resolve the issue by adding additional call checks.
- Example: https://travis-ci.org/recurly/recurly-js/jobs/296127480
> Fixes iOS 11 CI errors

- lib/errors.js
- lib/recurly.js
- lib/recurly/pricing/checkout/calculations.js
- lib/recurly/pricing/checkout/index.js
- lib/recurly/pricing/promise.js
- lib/recurly/pricing/subscription/embedded.js
- lib/recurly/pricing/subscription/index.js
- lib/recurly/tax.js
- package-lock.json
- package.json
- test/pricing/checkout/checkout.test.js
- test/pricing/subscription/embedded.test.js
- test/recurly.test.js
- test/server/fixtures/plans/basic-gbp.json
- test/server/fixtures/tax/index.js
- **To follow #391** -- includes CheckoutPricing gift card framework
- Adds `CheckoutPricing#tax`
- Adds `CheckoutPricing/Calculations#taxes` calculation routines
- Adds `CheckoutPricing#currency` change side effects
- Adds `CheckoutPricing` adjustment currency specification
```js
var checkoutPricing = recurly.Pricing.Checkout();
checkoutPricing
.adjustment({ amount: 20 })
.tax({ vatNumber: 'my-vat-number' })
.address({
country: 'US',
postalCode: '94117'
})
.done((price) => {
console.log(price)
});
```
```js
var checkoutPricing = recurly.Pricing.Checkout();
checkoutPricing.on('change', price => console.log(price));
// USD adjustment is active
checkoutPricing
.adjustment({ amount: 20, currency: 'USD' })
.adjustment({ amount: 15, currency: 'GBP' })
.done();
// disables USD adjustment, …
```
> CheckoutPricing: Taxes and Adjustment Currencies

- karma.conf.js
- lib/errors.js
- lib/recurly.js
- lib/recurly/apple-pay.js
- lib/recurly/paypal/strategy/index.js
- lib/recurly/pricing/checkout/calculations.js
- lib/recurly/pricing/checkout/index.js
- lib/recurly/pricing/index.js
- lib/recurly/pricing/promise.js
- lib/recurly/pricing/subscription/attachment.js
- lib/recurly/pricing/subscription/calculations.js
- lib/recurly/pricing/subscription/embedded.js
- lib/recurly/pricing/subscription/index.js
- lib/recurly/tax.js
- lib/util/decimalize-member.js
- lib/util/decimalize.js
- package-lock.json
- package.json
- test/apple-pay.test.js
- test/paypal/strategy/strategy.test.js
- test/pricing/checkout/checkout.test.js
- test/pricing/subscription/embedded.test.js
- test/recurly.test.js
- test/server/fixtures/plans/basic-gbp.json
- test/server/fixtures/tax/index.js
- **To follow #393** - includes `SubscriptionPricing` taxation methods and calculations, and adjustment currency determinations and calculations
- Adds `Pricing.totalNow` and `Pricing.currencyCode`
- Adapts `ApplePay` and `PayPalStrategy` base class to read `Pricing.totalNow` and `Pricing.currencyCode`
- Updates `PricingPromise` to the class pattern
```js
var checkoutPricing = recurly.Pricing.Checkout();
var payPal = recurly.PayPal({ pricing: checkoutPricing });
// checkoutPricing manipulations: add subscriptions, adjustments. coupons, gift cards, address info, tax info, etc
$('#my-checkout-form').on('submit', function (event) {
event.preventDefault();
// PayPal express checkout window will open with current Pricing totals and currency
payPal.start();
});
```
```js
var checkoutPricing = …
```
> CheckoutPricing: Apply Pay & PayPal support

- lib/recurly/apple-pay.js
- lib/recurly/paypal/strategy/braintree.js
- lib/util/after.js
- lib/util/deep-assign.js
- This is targeting `v4.8.0`
- Further reduces dist size
> Removes lodash.after dependency from BraintreeStrategy

- lib/recurly/paypal/index.js
Currently listeners registered to the cancel event don't get called for paypal/braintree. This fix makes them get called.
> fix bug with listener not registered for cancel event on paypal

- Makefile
- karma.conf.js
- lib/recurly.css
- lib/recurly.js
- package-lock.json
- package.json
- test/paypal/paypal.test.js
- test/server/fixtures/post-message.html.ejs
- webpack.config.js
- webpack.test.config.js
- Adds `recurly.css` to the build, to be included alongside `recurly.js`
- Provides default styles to match browser defaults as close as possible.
- Upgrades Webpack to v3
- Updating the spec order revealed that PayPal specs were leaving behind abandoned relay frames in IE
- These relays were halting because their messages violated `postMessage` rules for the [Structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm). This was resolved by correctly `JSON.stringify`ing the messages
- The Recurly bus was not parsing relay messages from these broken relays because they were improperly formatted
- Since the messages were failing in the relay, they were not getting back to the `Frame` instances and not ending the `Frame` session. …
> Adds default stylesheet recurly.css

- lib/recurly/pricing/checkout/attachment.js
- lib/recurly/pricing/checkout/calculations.js
- lib/recurly/pricing/checkout/index.js
- lib/recurly/pricing/subscription/embedded.js
- test/pricing/checkout/checkout.test.js
- Fixes propagation of subscription events like `set.plan` to their checkout
- Simplifies `CheckoutPricing/Attachment` subscription and adjustment handling, precisely removing and updating existing items in-place
- Updates adjustment data model to use `id` instead of `code` to make it compatible with pricing item expectations
- Fixes `CheckoutPricing/Attachment` `addon_price` output element assignment
> Fix checkout deferred emitters

- lib/recurly/pricing/checkout/index.js
- test/pricing/checkout/checkout.test.js
- Clears coupons from subscriptions on checkout coupon removal
- When a free trial coupon exists on a checkout, it is applied to the most valuable subscription. Removing that coupon from the checkout would not immediately remove it from the subscription, resulting in checkout calculations based on the prior free trial coupon.
> Fixes vestigial coupons on Checkout Calculations

- lib/recurly/pricing/checkout/calculations.js
- lib/recurly/pricing/checkout/index.js
- lib/recurly/pricing/index.js
- test/pricing/checkout/checkout.test.js
- test/server/fixtures/coupons/coop-fixed-all-500-eur.json
- Fixes Pricing.remove async completion
- Ensures removal has completed before proceeding to unset and retrieval of new coupon
- If a coupon does not support the checkout currency, it will not attempt to discount the checkout
> Fix checkout coupon currency safety

- karma.conf.js
- lib/recurly/apple-pay.js
- lib/recurly/pricing/index.js
- package-lock.json
- test/apple-pay.test.js
- Apple Pay cannot process zero amount transactions
- When a transaction is discounted to zero, we will authorize the card with a temporary one-unit-amount transaction
- This updates `recurly.ApplePay` to reflect this temporary authorization when the total has been reduced to zero via discount, free trial, or simply base price
```js
var applePay = recurly.ApplePay({
// ...
i18n: {
authorizationLineItemLabel: 'Temporary Card Authorization',
subtotalLineItemLabel: 'Subtotal',
discountLineItemLabel: 'Discount',
taxLineItemLabel: 'Tax',
giftCardLineItemLabel: 'Gift card'
}
});
```
> Apple pay zero amount authorizations

- lib/recurly/hosted-fields.js
- Adds a new `displayIcon` configuration value, which will inform a card field to not display its integrated card brand icon
```js
recurly.configure({
// ...
fields: {
card: {
displayIcon: false
}
}
// ...
});
```
> Adds displayIcon field configuration option pass-through

- CHANGELOG.md
- Release dates reflecting actual CDN release dates will now be published to [release notes](https://github.com/recurly/recurly-js/releases)
> Removes dates from CHANGELOG

- lib/recurly/apple-pay.js
- lib/recurly/bus.js
- lib/recurly/frame.js
- lib/recurly/hosted-field.js
- lib/recurly/hosted-fields.js
- lib/recurly/paypal/strategy/braintree.js
- lib/recurly/request.js
- lib/util/dom.js
- test/apple-pay.test.js
- test/configure.test.js
- test/paypal/paypal.test.js
- test/paypal/strategy/direct.test.js
- test/pricing/checkout/attachment.test.js
- test/pricing/subscription/attachment.test.js
- test/recurly.test.js
- test/support/helpers.js
- test/token.test.js
As mentioned in #455 it would be good to remove use of eval. To facilitate that change we need to remove use of `global` within the library and instead use `window`
> fix: switch to using window over global

- webpack.config.js
We wish to use `recurly.js` on a site which has a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) in place that does not permit `unsafe-eval` for `script-src` resources.
> 'unsafe-eval'
Allows the use of eval() and similar methods for creating code from strings. You must include the single quotes.
I believe that this is being introduced to your compiled codebase by Webpack. This thread has some further insight into people's experience here [#5627 Calling Function or eval should be eliminated as a security measure and would cause the application execution to be halted if the document CSP header has script-src 'self'; ](https://github.com/webpack/webpack/issues/5627)
> chore: remove eval from minified file

- lib/util/tax-ceil.js
- test/pricing/checkout/checkout.test.js
- test/server/fixtures/coupons/coop-fixed-all-5.json
- Occurs if a merchant sets all items on a checkout to be tax exempt
- If a blanket amount discount is applied, then taxes will be subtracted according to the discount amount. Since discounts are not exampt-able, a negative tax amount would occur
> Fixes issue where tax exemption results in negative taxes

- lib/util/web-storage.js
- test/util/web-storage.test.js
- If localStorage or sessionStorage are not available in the current environment, WebStorage will fall back to a POJO pattern of storage.
> Adds Storage availability check and generic object fallback scenario

- lib/util/web-storage.js
- webpack.config.js
- When chrome users disable third-party cookies, iframes from recurly.com on merchant pages are forbidden from accessing localStorage. This catches exceptions in that scenario and presents the objectStore as a replacement
> Fixes storage availability check within hosted fields

- test/adyen.test.js
Adds missing tests for the Adyen functionality, specifically for payload validations after invoking the payment modal.
> Backfill AdyenHPP tests

- lib/recurly/pricing/subscription/attachment.js
Fixes a problem where only the first addon is calculated when the pricing module is attached to a form which already has multiple addon elements
> Fix pricing calculation for multiple addons

- .travis.yml
- lib/recurly/pricing/index.js
- lib/recurly/pricing/subscription/index.js
- test/pricing/subscription/subscription.test.js
- When switching plans on a `SubscriptionCheckout` instance,
the constituent discounts must be checked for compatibility and
removed accordingly
- Fixes #488
> Fixes coupon resolving when switching subscription plans

- package-lock.json
- package.json
fsevents has a MacOS dependency.  Making this package optional will allow for builds on linux and other non-mac systems.
> Make fsevents optional to allow for builds on linux systems

- karma.ci.conf.js
- karma.conf.js
- package-lock.json
- package.json
- webpack.config.js
- Fixes #496 
- After #483, the CI environment began integrating an `Object.assign` polyfill across all test environments, masking an issue introduced in the same change where `Object.assign` calls were not transformed. This broke IE11 in the build, but prevented unit tests from identifying the issue.
- This change restricts the application of `karma-phantomjs-shim` to only runs which utilize Phantom.
- In the near future, #491 will obviate the need for the PhantomJS shim, removing this risk entirely
> Fixes CI shimming and Object.assign introduction

- lib/recurly/hosted-fields.js
- test/hosted-fields.test.js
- When configuring an individual hosted field, the format config option would not be passed correctly to the field itself
> Fixes determination of individual field formatting configuration

- index.js
- lib/recurly.js
- lib/recurly/adyen.js
- lib/recurly/bus.js
- lib/recurly/frame.js
- lib/recurly/fraud.js
- lib/recurly/hosted-field.js
- lib/recurly/hosted-fields.js
- lib/recurly/message.js
- lib/recurly/reporter.js
- test/hosted-fields.test.js
- test/server/fixtures/field.html.ejs
- Allows multiple `recurly` instances to co-exist in a single `window`
- Adds a `bus.groupId` uuid which identifies `Messages` intended to be isolated to a particular `Bus` group
- A `recurly` instance will pass its `groupId` along to its dependent hosted fields, allowing those hosted fields to isolate their messages to that `recurly` instance.
- Improves `Message` parsing across relays
> Isolates buses across instances

- .travis.yml
- karma.conf.js
- lib/recurly/bus.js
- test/adyen.test.js
- test/bus.test.js
- test/support/fixtures.js
- Type checking a cross-domain window property throws an error in Edge 44 (EdgeHTML 18)
- This replaces property detection with prototype chain inspection
- Fixes #509
> Fixes Edge 44 bug when adding an iframe as a bus recipient

- lib/recurly/pricing/checkout/attachment.js
- lib/recurly/pricing/checkout/calculations.js
- lib/recurly/pricing/checkout/index.js
- lib/recurly/pricing/index.js
- lib/recurly/pricing/subscription/attachment.js
- lib/recurly/pricing/subscription/calculations.js
- lib/recurly/pricing/subscription/index.js
- test/apple-pay.test.js
- test/pricing/checkout/attachment.test.js
- test/pricing/checkout/checkout.test.js
- test/pricing/subscription/attachment.test.js
- test/pricing/subscription/subscription.test.js
- test/support/fixtures.js
- Adds amount param to tax methods on each
- Adds tax_amount_now and tax_amount_next input detection to Attachment classes
- Adds tax calculation overrides to Calculations classes
When amount is specified, all tax calculations are overridden. Vat numbers, tax codes, and exemption rules are ignored.
```js
const subscriptionPricing = recurly.Pricing.Subscription();
subscriptionPricing
.plan('basic')
.tax({
amount: {
now: '20.01',
next: '5.09'
}
}).done(function (price) {
price.now.tax; // '20.01'
price.next.tax; // '5.09'
});
```
```js
const checkoutPricing = recurly.Pricing.Checkout();
checkoutPricing
.subscription(subscriptionPricing)
.adjustment({ amount: '5' })
.taxes({
amount: {
now: '20.01',
next: '5.09'
}
}).done(function (price) {
price.now.taxes; // '20.01'
price.next.taxes; // …
```
> Adds specific tax amount overrides to SubscriptionPricing and CheckoutPricing

- lib/recurly/pricing/checkout/index.js
- lib/recurly/pricing/index.js
- package-lock.json
- package.json
Removes the dependency on isFinite from lodash in favor of the native method instead.
> Remove lodash isFinite dependency

- lib/recurly/frame.js
- lib/recurly/paypal/strategy/direct.js
- test/frame.test.js
- test/paypal/strategy/direct.test.js
Fixes #520 
This allows library users to listen for a `cancel` event that is emitted when the popup window for PayPal closes.
Example usage:
```javascript
this.paypal.on('cancel', () => {
// react to the window closing
});
```
> Emit PayPal cancel event on frame close

- lib/recurly/risk/three-d-secure/strategy/braintree.js
When loading the Braintree libraries the code checks if `window.braintree.client` and `window.braintree.threeDSecure` exist, but not `window.braintree`. The first time the `loadBraintreeLibraries` method is called it throws an error: `TypeError: "window.braintree is undefined"`. This PR adds the additional check for `window.braintree` to avoid the error 🙂
> Fixes loading Braintree libraries

- lib/recurly/risk/three-d-secure/strategy/braintree.js
- test/risk/three-d-secure/strategy/braintree.test.js
- test/server/fixtures/tokens/action-token-adyen-3ds1.json
- test/server/fixtures/tokens/action-token-adyen-fingerprint.json
- test/server/fixtures/tokens/action-token-adyen.json
- test/server/fixtures/tokens/action-token-braintree.json
- test/server/fixtures/tokens/action-token-sage-pay.json
- test/server/fixtures/tokens/action-token-stripe.json
- test/server/fixtures/tokens/action-token-test.json
- test/server/fixtures/tokens/action-token-wirecard.json
- test/server/fixtures/tokens/action-token-worldpay.json
- Updates API mocks
- Sends correct amount to Braintree 3DS client to ensure the amount displayed reflects expectation.
> Fixes Braintree authentication amount display

- lib/recurly/frame.js
- lib/recurly/risk/three-d-secure/strategy/adyen.js
- lib/recurly/risk/three-d-secure/strategy/sage-pay.js
- lib/recurly/risk/three-d-secure/strategy/test.js
- lib/recurly/risk/three-d-secure/strategy/wirecard.js
- lib/recurly/risk/three-d-secure/strategy/worldpay.js
- test/frame.test.js
- test/risk/three-d-secure/strategy/adyen.test.js
- test/risk/three-d-secure/strategy/test.test.js
- test/risk/three-d-secure/strategy/wirecard.test.js
- test/risk/three-d-secure/strategy/worldpay.test.js
I'm thinking there's a better way to implement this that doesn't involve exporting/import `TYPE`, but I don't know what that would be.
With a static property as suggested in the ticket, I wasn't able to figure how to use that outside of the class when creating an instance of Frame (i.e., `const frame = new Frame({ type: Frame.TYPES.IFRAME });` or something like `Frame({ type: this.constructor.TYPES.IFRAME });` or `Frame({ type: this.TYPES.IFRAME });`
If I'm missing something, I'm open to changing anything.
> updates Frame to use enum instead of string types

- karma.conf.js
- lib/recurly/frame.js
- test/frame.test.js
This fixes the issue in the title by calling `clearInterval` on the tick that polls the window when a paypal action is successful.
> Fixes an issue with paypal incorrectly emitting a cancel event on success

- .travis.yml
- karma.conf.js
- lib/recurly.js
- lib/recurly/errors.js
- lib/recurly/item.js
- lib/recurly/pricing/checkout/attachment.js
- lib/recurly/pricing/checkout/index.js
- test/giftcard.test.js
- test/item.test.js
- test/pricing/checkout/checkout.test.js
- test/server/fixtures/items/basic-item-eur.json
- test/server/fixtures/items/basic-item.json
- test/server/fixtures/items/invalid.json
- test/server/fixtures/plans/invalid.json
- test/server/index.js
`CheckoutPricing#adjustment` will now accept an `itemCode`, which Recurly.js will use to retrieve price information when constructing an adjustment. Overrides are accepted for amount.
When modifying an existing adjustment that was created with an `itemCode`, the `taxCode` and `taxExempt` properties may not be modified.
Bonus: Improves documentation of `CheckoutPricing` class
> Checkout pricing items

- lib/recurly/validate.js
- test/validate.test.js
**Description**:
Add new Discover BINs:
https://www.discoverglobalnetwork.com/downloads/IPP_VAR_Compliance.pdf
**Impact**:
* New Discover card number ranges supported
* CC numbers may be as long at 19 digits
**Testing**:
* Ensure that all credit card number fields can accept up to 19 digits plus 4 spaces. (Note that the card itself may be rejected by the payment gateway for excessive length...)
* Ensure that all Discover card number ranges are recognized by `recurly.js`.
A few random credit card numbers you can use:
* 3642114894729353156
* 3006328989305540860
* 6011780540223945424
* 6210947425951487417
* 6221279415221686517
* 6221651960770601237
* 6229599417949687204
* 6285961264133421617
* 6459900460534704497
* 6583963952116788557
* 8125064527526848810
* 8171136375604275463
> Add new Discover BINs

- .travis.yml
The environment is now stable in BrowserStack
> Adds iOS 13 to CI runs

- lib/recurly/pricing/subscription/calculations.js
- test/configure.test.js
- test/pricing/checkout/checkout.test.js
- test/pricing/subscription/subscription.test.js
- test/server/fixtures/plans/free-trial-no-setup.json
- test/server/fixtures/plans/free-trial.json
**Summary**
- Fixes #572
- Adds test scenarios for applying a single-use fixed coupon to
(a) a free trial subscription with a setup fee
(b) a free trial subscription without a setup fee
**Situation**
- When pricing a subscription with a free trial plan with no setup fee
- Apply a fixed amount single-use coupon. Since the first invoice will
be zero, the coupon should discount the next invoice. This second
invoice was not being discounted.
**Solution**
- The next period discount should only be zeroed out if the coupon is
both single_use and has had no discount effect on the first period
discount
> Fixes discount calculations on free trial subscriptions with a single-use coupon

- lib/recurly.js
- lib/recurly/hosted-fields.js
- test/configure.test.js
- test/recurly.test.js
**Summary**
- Fixes #570
- When `recurly.configure` was called during readyState 1, it was not
possible to reset hosted fields.
**Scenario**
- `recurly.configure`[call 1] instantiates `recurly.hostedFields`. The fields are created.
- the fields are removed from the DOM prior to emission of the ready message
- the advancement listener does not increment `recurly.readyState`, which remains `1`
- `recurly.configure`[call 2 and on] is called, and the reset routine is bypassed due to incompatible readyState
**Solution**
- This allows reset to occur at `readyState > 0`, essentially any time the hostedFields have begun initialization.
- If, during reset, the current readyState is 1, the awaiting listeners are abandoned in order to prevent the stale advancement listener from interfering with the …
> Fixes HostedFields reset on re-configuration preceding initialization

- lib/recurly/bank-account.js
- lib/recurly/validate.js
- package-lock.json
- package.json
- test/bank-account.test.js
- test/server/fixtures/token/index.js
- test/server/fixtures/tokens/index.js
- test/server/index.js
- webpack.test.config.js
**Summary**
- Adds tokenization support for IBAN bank accounts to `recurly.bankAccount.token`
**Usage**
```html
<form id="iban-form">
<input type="text" data-recurly="name_on_account" placeholder="Name on Account">
<input type="text" data-recurly="iban" placeholder="IBAN">
</form>
```
```js
recurly.bankAccount.token(document.querySelector('#iban-form'), (err, token) => {
if (err) {
// handle err
} else {
// token.type => 'iban_bank_account'
// token.id
}
});
```
> Adds support for tokenizing IBAN Bank accounts

- karma.ci.conf.js
Fixes CI failures by ensuring `localIdentifier` is specified to browserstack, ensuring connection success.
> Specifies local and debug options for unit tests run in Browserstack

- lib/recurly/paypal/index.js
- lib/recurly/paypal/strategy/braintree.js
- lib/recurly/paypal/strategy/direct.js
- test/types/paypal.ts
- test/unit/paypal/paypal.test.js
- test/unit/paypal/strategy/braintree.test.js
- test/unit/paypal/strategy/direct.test.js
- test/unit/support/helpers.js
- types/paypal.ts
Need to add tests for this
- Adds PayPalStrategy#destroy
- Adds '- DirectStrategy#destroy
- Adds '- BraintreeStrategy#destroy
- Will remove listeners, unwind dependencies, and destroy active dependent frames
> Adds PayPal#destroy

- .travis.yml
Browserstack infrastructure has resolved the issues blocking iOS 13 unit tests.
> Restores iOS 13 CI tests

- lib/recurly/apple-pay.js
This will help determine more narrow transaction capabilities
> Sends requested currency in `GET /apple_pay/info` requests

- lib/recurly/plan.js
Previously, when an empty string was passed to the plan function as the code param, a network request would initiate to /js/v1/plan/?<params>, resulting in a network error.
This improves error messaging by throwing a "Missing plan code" error when the plan code is empty instead of a generic network error.
> Throws missing plan code error if plan is an empty string

- test/types/bank-account.ts
This fixes a gap in our testing for bankAccount.token. It looks like I originally wrote the same test twice for the first parameter as an HTMLFormElement and forgot to test for BillingInfo.
> Fixes BankAccount type test

- .github/workflows/release-notes.yaml
- the ref substitution does not properly handle the git tag ref prefix. This addresses that, and will fix the automated release notes generation.
> Fixes release notes version determination

- .github/workflows/dt.yaml
- Makefile
- test/types/token/hosted-field.ts
- test/types/tsconfig.json
- types/index.d.ts
- types/lib/emitter.d.ts
- types/tsconfig.json
- types/tslint.json
DefinitelyTyped PR here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45675 with checks passing triggered from this PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45675/checks?check_run_id=852435520
Previously, we only ran tests on test/types, but DefinitelyTyped is also linting the types themselves, not just the tests, resulting in potential undiscovered linting errors emerging when opening our PR to DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45675/checks?check_run_id=801301793)
To fix this, we're now linting our types with dtslint. We had to move types/ to DefinitelyTyped/types/recurly__recurly-js to circumvent this error https://github.com/microsoft/dtslint/blob/master/src/index.ts#L214-L227
This was also added as a CI step.
We had …
> Patches dtslint config to match DefinitelyTyped

- types/lib/paypal.d.ts
I'm pretty sure this method (PayPal.token) doesn't exist and was added in error.
> Removes nonexistent token method from PayPal.d.ts

- test/types/bank-account.ts
- test/types/index.d.ts
- types/lib/bank-account.d.ts
The goal here is to update the types for BankAccount so they reflect the runtime as accurately as they can. These changes are intended to provide type checking around the shape of the object getting passed to `BankAccount.token` by breaking down `BillingInfo` into its base payment types (ACH, SEPA, BACS, BECS).
> Enhances types for BankAccount

- Makefile
- the dependent target was mislabeled
> Fixes test-unit-debug Make target

- .travis.yml
> Allows react-recurly unit test step to fail when the Travis build is for a PR

- .github/workflows/dt.yaml
- test/types/bank-account.ts
- test/types/configure.ts
- test/types/paypal.ts
- test/types/recurly-error.ts
- test/types/tsconfig.json
- types/lib/configure.d.ts
- types/lib/elements.d.ts
- types/lib/paypal.d.ts
1. Adds types for configuring recurly.js with hosted fields (https://github.com/recurly/recurly-js/issues/646)
2. Updates types for PayPal events to includes `cancel` and `ready` (https://github.com/recurly/recurly-js/issues/646)
3. Fixes `element.style.invalid` type by making it optional instead of required
4. Fixes scoped package naming
> TypeScript updates and fixes

- lib/recurly/risk/three-d-secure/strategy/worldpay.js
- test/e2e/display.test.js
- test/unit/risk/three-d-secure/strategy/worldpay.test.js
Remove redirectURL from WorldpayStrategy so that we can dynamically change development vs production URLS in RA.
> remove redirectURL from WorldpayStrategy

- lib/recurly/risk/three-d-secure/strategy/braintree.js
- test/unit/risk/three-d-secure/strategy/braintree.test.js
Include suggested parameter to override the default behavior of 3DS2 for Braintree and request the cardholder's bank to issue an authentication challenge.
> add gateway suggested field to braintree 3ds flow

- lib/recurly/paypal/strategy/direct.js
- lib/recurly/paypal/strategy/index.js
- test/unit/paypal/strategy/direct.test.js
Include `gatewayCode` as a parameter to allow for specific PayPal gateway routing when multiple PayPal gateways enabled.
> Select PayPal gateway

- lib/recurly/risk/three-d-secure/three-d-secure.js
This PR changes our processing of the preflights to run authentication calls and device data collection calls in Promises that resolve sequentially instead of all at once in a Promise.all as before.
This is because the event listeners instantiated in risk strategies during this process were previously all receiving the same event since the events do necessarily have unique identifiers.
> Sequential Preflight Calls

- lib/recurly/apple-pay/apple-pay.js
- test/unit/apple-pay.test.js
Requires the device to not support v4 (Mojave)
Highlights include:
- Adds ApplePay merchant configuration property [`supportedCountries`](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymentrequest/2928612-supportedcountries)
- Supports $0 totals (common use case is free trials)
> Update Minimum Apple Pay Version to v4

- lib/recurly/risk/three-d-secure/strategy/stripe.js
When attaching the stripe js elements, it may throw depending on the payment intent status.
This PR properly handles the errors to avoid waiting indefinitely for the challenge that will not appear and fail the transaction.
> Handle stripe js error when attaching the stripe element

- lib/recurly.js
- lib/recurly/fraud.js
- test/unit/fraud.test.js
- test/unit/support/fixtures.js
This PR will allow for multiform fraud detection. It will attach data-recurly=“fraud_session_id” to multiple forms. In addition it will allow for our RiskDataCollector component to work with Kount configured. Without this change when using our react component we would not see a session id populated to the form to be submitted on tokenization. In a similar fashion, without this change, when using multiple forms/multiple calls to recurly.configure with our rjs library we would not see the fraud session id attached to additional forms added to the page after an initial call to recurly.configure.
Testing:
Create a page utilizing the recurly-js library with 2 forms. 
Use the following recurly-js script and stylesheet: 
```
<script src="https://js.qa2.recurlyqa.com/v4/recurly.js"></script> …
```
> Multi form fraud detection

- lib/recurly/apple-pay/apple-pay.js
- test/server/fixtures/apple_pay/info.json
- test/unit/apple-pay.test.js
Upgrades the native ApplePay integration to:
- Utilize the merchant Recurly subdomain as the `applicationData` if present
- Submit the customer browser hostname when retrieving the merchant config and starting the AP session.
Ensure that both the native and Braintree AP integrations continue to function.
> [feat][apple-pay] send hostname to server and specify applicationData

- .travis-pre.sh
Recent [builds](https://app.travis-ci.com/github/recurly/recurly-js/jobs/596366679) in TravisCI are failing in the "Publish Artifacts" step with this error:
```
The command "make build" exited with 0.
1.13s$ gsutil cp -Z build/* $GCS_BUCKET_URL/$TRAVIS_COMMIT/
Traceback (most recent call last):
File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil", line 21, in <module>
gsutil.RunMain()
File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil.py", line 121, in RunMain
import gslib.__main__
File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 83, in <module>
import httplib2
ModuleNotFoundError: No module named 'httplib2'
The command "gsutil cp -Z build/* $GCS_BUCKET_URL/$TRAVIS_COMMIT/" exited with 1.
cache.2
```
This PRs adds the missing PIP packages (`httplib2` and …
> Installing `httplib2` and `crcmod` as needed by `gsutil` in the last build step

- lib/recurly/pricing/subscription/calculations.js
- lib/recurly/pricing/subscription/index.js
- lib/recurly/pricing/subscription/tiered-pricing-calculator.js
- test/server/fixtures/plans/tiered-plan.json
- test/unit/pricing/subscription/tiered-pricing-calculator.test.js
Fixes addressed in this PR:
* Fix prices calculated for each tiered addon, now considering the `quantity` amount for inputs using `data-recurly="addon_price"`.
Before this change the price for addons in these points were being calculated using the largest tier:
* `subscription.price.base.addons['addon-code']` 
* `subscription.price.addons['addon-code']`
* Fix total and subtotal calculation when having multiple addons for the same subscription
> Fix Tiered Unit Pricing Labels

- lib/recurly/google-pay/google-pay.js
- test/unit/google-pay/google-pay.test.js
There are certain conditions in which Recurly needs the full `paymentData` from the Google response.
> [feat][google-pay] send raw payment data to server

- lib/recurly/apple-pay/apple-pay.braintree.js
- lib/recurly/apple-pay/apple-pay.js
- lib/recurly/apple-pay/util/transform-address.js
- lib/recurly/token.js
- test/types/apple-pay.ts
- test/unit/apple-pay.test.js
- types/lib/apple-pay/index.d.ts
- types/lib/apple-pay/native.d.ts
Apple Pay on the Web supports supplying a `billingContact` and
`shippingContact` when creating the session. If provided, it would
populate over the customer's default billing contact on the payment
sheet.
If the `form` option is supplied, use the address fields that are
populated to populate the `billingContact` and the shipping fields
that are populated to populate the `shippingContact`.
This also cleans up the interaction between the `form` and the token.
Currently, if any of the fields on the `form` are present, we prefer
that address instead of what is presented and modified on the payment
card. This changes that functionality to always prefer the
`billingContact` from the payment card when tokenizing the card as
that is what the customer sees when authorizing the payment.
> feat(apple pay): populate billingContact with form address fields

- lib/recurly/apple-pay/apple-pay.js
- lib/recurly/apple-pay/util/transform-address.js
- lib/recurly/pricing/index.js
- lib/recurly/pricing/subscription/calculations.js
- lib/recurly/pricing/subscription/index.js
- test/unit/apple-pay.test.js
- test/unit/pricing/checkout/attachment.test.js
- test/unit/pricing/subscription/attachment.test.js
When `options.pricing` is supplied to `recurly.ApplePay`, tax will be recalculated and stored based on the client's selection on the payment sheet for both billing and shipping contacts (shipping requires collecting the `postalAddress`).
Internally this changes the `SubscriptionPricing#items` schema from `items.shipping_address` to `items.shippingAddress` to match the `CheckoutPricing#items` schema. It does not change the `set.shipping_address` event that is emitted, however.
> feat(apple pay): update tax when billing/shipping contact changes

- lib/recurly/apple-pay/util/build-apple-pay-payment-request.js
- test/unit/apple-pay.test.js
- types/lib/apple-pay/native.d.ts
Opens up the `supportedNetworks` option for the merchant to choose which networks they would like to accept. This list must be a subset of the merchant's accepted networks in Recurly.
> feat(apple pay): allow for supportedNetworks selection

- lib/recurly/apple-pay/apple-pay.js
- lib/recurly/apple-pay/util/finalize-apple-pay-payment-request.js
- lib/recurly/apple-pay/util/transform-address.js
- test/unit/apple-pay.test.js
Pricing is the recommended way of integrating with Recurly.js, so use the `address` and `shippingAddress` properties of the `price` to populate the `billingContact` and `shippingContact` over the `form` address. The `address.phone` is part of the `shippingContact` in Apple terms so it shows in the payment sheet.
> feat(apple pay): populate contacts with pricing addresses

- lib/recurly/apple-pay/apple-pay.js
When restoring the `address` and `shippingAddress` on `pricing` after the user cancels, we do not emit the change event if the addresses were to change. This fixes that so we are consistent in changing the addresses during the AP checkout flow.
> fix(apple pay): emit events when restore pricing addresses

- test/unit/apple-pay.test.js
When there is an error thrown in an async test, Mocha will time out instead of fail with the error that is thrown. This adds a `ensureDone` helper function to wrap the callbacks and capture the error to the logs so there is visibility into what actually failed.
> chore(apple pay): capture async test errors to fail faster

- lib/recurly/apple-pay/apple-pay.js
- lib/recurly/apple-pay/util/apple-pay-line-item.js
- lib/recurly/apple-pay/util/build-apple-pay-payment-request.js
- test/server/fixtures/apple_pay/info.json
- test/types/apple-pay.ts
- test/unit/apple-pay.test.js
- types/lib/apple-pay/index.d.ts
- types/lib/apple-pay/native.d.ts
Cleans up the interface for calling into `recurly.ApplePay` so that the
properties that drift down to the resulting payment request are not
intermixed with the SDK specific parameters.
As a result, deprecates `options.requiredShippingContactFields` in favor
of reading it off of the `paymentRequest.requiredShippingContactFields`.
Adds `options.recurring` that, when provided in combination with
`options.total`, will create a total that will include a monthly
recurring charge on the payment sheet.
`options.paymentRequest` will be treated as the source of truth, except
for when `options.pricing` is provided. This maintains the stance that
Pricing controls the `total` and `lineItems`.
Can be will be generated if the `total` line item is set to `paymentTiming='recurring'`:
```typescript
const …
```
> feat(apple pay): add support for `recurringPaymentRequest`, move to `options.paymentRequest`

- types/lib/apple-pay/index.d.ts
Recurly.js now accepts the `requiredShippingContactFields` option: https://recurly.com/developers/reference/recurly-js/#apple-pay but attempting to set this option in a typescript setup will result in a TS error.
> Update config type with requiredShippingContactFields

- lib/recurly/apple-pay/apple-pay.js
- test/types/apple-pay.ts
- test/unit/apple-pay.test.js
- types/lib/apple-pay/index.d.ts
- types/lib/apple-pay/native.d.ts
Adds the `options.callbacks` option which supports the following
callbacks:
- `onPaymentMethodSelected`
- `onShippingContactSelected`
- `onShippingMethodSelected`
- `onPaymentAuthorized`
to correspond with the `ApplePaySession` events.
A callback must return either the Apple Pay update object or a Promise
that resolves with that object.
That update object will be used to complete the `ApplePaySession` event
to open up the ability to fetch custom taxes on payment method selection,
update shipping costs on shipping contact/method selection and validate
email/phone addresses on authorization.
This does not remove the existing events being emitted but the workflow
should be updated to prefer using `onPaymentAuthorized` to complete the
purchase instead of async on the `token` event. The event …
> feat(Apple Pay): allow for customization of event updates

- lib/recurly/apple-pay/apple-pay.braintree.js
- test/unit/apple-pay.test.js
`teardown` completely removes the Braintree instance which will cause issues if the client cancels and tries to initialize a payment. This is not needed as beginning a session does not reinitialize the BT client, so we can have successive attempts on the same client.
Fixes the `performValidation cannot be called after teardown` error on subsequent tries.
> fix(apple pay): Do not teardown Braintree on cancel

- lib/recurly/apple-pay/apple-pay.js
- test/unit/apple-pay.test.js
When a callback returns a promise, R.js was using `finally` to update the payment sheet, however `finally` does not accept any arguments so no updates were actually propagated through to the payment sheet. This fixes that by using a `catch.then` to ensure that the promise is handled value is propagated correctly.
> fix(apple pay): callbacks with promises resolve correctly

- lib/recurly/apple-pay/apple-pay.js
- lib/recurly/apple-pay/util/build-apple-pay-payment-request.js
- lib/recurly/venmo/strategy/braintree.js
- test/unit/apple-pay.test.js
- types/lib/apple-pay/index.d.ts
- types/lib/apple-pay/native.d.ts
[simplify newRecurringPaymentRequest handling](https://github.com/recurly/recurly-js/pull/815/commits/7ab71ce96ca58b6a754373ab4e618bd7f0273165) 
There are a variety of methods to initialize ApplePay with various
levels of integration with the native ApplePay request. On the simplest
level of configuration (`total`, `recurring` options), the merchant
might want to register the `onPaymentMethodSelected` callback to update
the total. Since the library creates the `recurringPaymentRequest` for
them automatically, we need to keep that total up to date if it changes.
We also manage the managementURL, so that property can be omitted when using the callback and added in automatically by the library.
[allow total to be specified on update …
> fix(apple pay): simplify newRecurringPaymentRequest handling

- lib/recurly/apple-pay/apple-pay.js
- lib/recurly/apple-pay/util/build-apple-pay-payment-request.js
- test/server/fixtures/apple_pay/info.json
- test/unit/apple-pay.test.js
- types/lib/apple-pay/index.d.ts
- types/lib/apple-pay/native.d.ts
- types/lib/google-pay/native.d.ts
Emits the `couponCodeChanged` event on the `recurly.ApplePay` instance and allows for `options.callbacks.onCouponCodeChanged` to receive the [`ApplePayCouponCodeChangedEvent `](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaycouponcodechangedevent) from Apple.
Note that this does not automatically hook into the `pricing.couponCode` entry as I could not get it to update the pricing in my testing, will follow up on that later but having base level support was requested.
> Add ApplePay coupon code changed support

- test/unit/risk/three-d-secure/strategy/paypal-complete.test.js
Remove `.only` in tests that prevented other tests from running
> Remove .only in tests that prevented other tests from running

- lib/recurly/risk/three-d-secure/strategy/paypal-complete.js
- packages/public-api-fixture-server/fixtures/tokens/action-token-paypal-complete.json
This PR renames PayPalCommerce to PaypalComplete
> Renamed PayPalCommerce to PayPalComplete

- .github/workflows/publish-types.yaml
- lib/recurly/apple-pay/apple-pay.braintree.js
- lib/recurly/apple-pay/util/build-apple-pay-payment-request.js
- test/unit/apple-pay.test.js
- types/lib/apple-pay/index.d.ts
- types/lib/apple-pay/native.d.ts
*  Support Merchant displayName for Braintree through `options.braintree.displayName`
*  Support requiredBillingContactFields overrides through `options.paymentRequest.requiredBillingContactFields`
> feat(apple pay): Improve support

- lib/recurly/paypal/strategy/braintree.js
- lib/recurly/venmo/strategy/braintree.js
Update to latest version of Braintree JS Client from `3.76.0` to `3.96.0`
> Update to latest version of Braintree JS Client

- lib/recurly/fraud.js
- lib/recurly/token.js
This will add additional logging for our Kount integration, from initialization through tokenization, if configured correctly through recurly-js.
> add kount debugging

- lib/recurly/errors.js
- lib/recurly/risk/three-d-secure/three-d-secure.js
- test/unit/risk/three-d-secure.test.js
When multiple purchases are attempted for the same customer/card within a similar timeframe, multiple 3DS challenges can occur which can cause issues with authorization on some gateways. This will prevent multiple challenges from existing and throw an error which indicates that another challenge already exists.
> Prevent multiple 3ds instances

- lib/recurly/google-pay/google-pay.js
- lib/recurly/google-pay/pay-with-google.js
- test/unit/google-pay/google-pay.test.js
- types/lib/google-pay/index.d.ts
Adds support for `IsReadyToPayRequest.existingPaymentMethodRequired` to emit a `google-pay-not-available` error and not render the button if the user does not have a card that is supported by merchant's gateway configuration.
This can be configured via the `existingPaymentMethodRequired` option in `recurly.GooglePay`.
> feat(google pay): Add support for `existingPaymentMethodRequired`

- lib/recurly.js
- lib/recurly/amazon/amazon-pay.js
- lib/recurly/amazon/index.js
Create frame that calls start endpoint and initiates checkout flow
> Add Amazon Pay

- lib/recurly/pricing/checkout/calculations.js
- test/unit/pricing/checkout/checkout.test.js
When utilizing single-use coupons, the `next` object in RJS was miscalculating the tax, falling back on the `now` objects subtotal for calculations. This resulted in lower taxes for the `next` object.
Gating the logic of the `next` object's `discountAmount` behind whether `coupon.single_use` is being used ensures the next object's discount amount applies properly.
> fix tax calculations on next object with single-use coupons

- lib/recurly/amazon/amazon-pay.js
Update to send along gatewayCode if merchant has multiple instances of Amazon Pay V2
> pass gateway_code to choose if multiple Amazon gateway instances

- types/lib/apple-pay/native.d.ts
Per [this file](https://github.com/recurly/recurly-js/blob/master/lib/recurly/apple-pay/apple-pay.js#L394), `recurlyToken` is attached to the `payment` field.
> Update ApplePayPaymentAuthorizedEvent type to match actual object shape

- lib/recurly/amazon/amazon-pay.js
- lib/recurly/risk/three-d-secure/strategy/amazon.js
- lib/recurly/risk/three-d-secure/three-d-secure.js
Amazon Pay transactions created against the Amazon UK and Amazon EU regions can trigger 3DS. 
This new class allows us to handle presenting the challenge to customers.
> Handle Amazon Pay 3DS action tokens

- lib/recurly/element/element.js
- lib/recurly/token.js
Support for Co-Badged cards. RJS will now emit an event, 'coBadge' that devs can listen for to display to their customers. This event will emit only for cards that support two networks. Customers should be presented these options and then select a preferred network which can be passed in the tokenization call via the attribute `data_recurly` with a value of `card_network_preference`.
> Co-badge card support

- lib/recurly/amazon/amazon-pay.js
- types/lib/amazon-pay.d.ts
The AmazonPay window was incorrectly emitting an `error` event when the user manually closed the recurly window frame. The `cancel` event should be emitted instead.
> fix: Amazon Pay should be emitting the 'cancel' event when the window is manually closed

- scripts/prepare-release
- types/package.json
DefinitelyTyped now [requires that the types contain a package.json file](https://github.com/DefinitelyTyped/DefinitelyTyped?tab=readme-ov-file#packagejson).
This update will add that file and the process to keep it's version in sync with the main RJS package.
> Adding types/package.json

- lib/recurly/alternative-payment-methods/alternative-payment-methods.js
- lib/recurly/alternative-payment-methods/gateways/adyen.js
- types/lib/alternative-payment-methods.d.ts
Allows any `billingAddress` applied to an `AlternativePaymentMethods#submit` call to be applied to tokens generated with CashApp.
> Adds billing address override to CashApp implementation

- lib/recurly/errors.js
- lib/recurly/google-pay/google-pay.js
- lib/recurly/google-pay/index.js
- lib/recurly/google-pay/pay-with-google.js
- test/e2e/support/helpers.js
- test/unit/apple-pay.test.js
- test/unit/google-pay/google-pay.test.js
- test/unit/paypal/strategy/complete.test.js
To better align the Google Pay element with the Apple Pay element, this refactors it to be a concrete class instead of a function. This will help in the future when we need to specialize its functionality for a different implementation of collecting the payment information. Adding Braintree support is an example of that specialization.
> chore: convert Google Pay element to a class from function

- lib/recurly/pricing/subscription/calculations.js
- Follow-up to https://github.com/recurly/recurly-js/pull/888
> Ensures setup fees are not applied to subscriptions with quantity = 0

- lib/recurly/google-pay/google-pay.braintree.js
- lib/recurly/google-pay/index.js
- package-lock.json
- package.json
- test/unit/google-pay/google-pay.test.js
- types/lib/google-pay/index.d.ts
_Best viewed without [whitespace](https://github.com/recurly/recurly-js/pull/894/files?w=1)_
To use Google Pay through Braintree, ensure that you have enabled
Google Pay on a Braintree gateway in the Recurly Admin UI and on your
Braintree account.
Then, initialize `recurly.GooglePay(...)` with the
`braintree.clientAuthorization` option:
```js
const googlePay = recurly.GooglePay({
...options,
gatewayCode: '<Recurly Braintree gateway code>',
braintree: {
clientAuthorization: '<Braintree client authorization key>',
},
})
```
> feat: Add Google Pay through Braintree

- lib/recurly/alternative-payment-methods/alternative-payment-methods.js
- lib/recurly/alternative-payment-methods/gateways/adyen.js
- test/unit/alternative-payment-methods/alternative-payment-methods.test.js
Adds destroy method to `alternative-payment-methods`. Calling this method removes and destroys the adyen web component, allowing it to subsequently be re-rendered without a page reload.
> Add destroy method for AlternatePaymentMethod class

- lib/recurly.js
- lib/recurly/risk/risk.js
- lib/recurly/risk/three-d-secure/strategy/braintree.js
- lib/recurly/risk/three-d-secure/strategy/cybersource.js
- lib/recurly/risk/three-d-secure/strategy/strategy.js
- lib/recurly/risk/three-d-secure/strategy/worldpay.js
- lib/recurly/risk/three-d-secure/three-d-secure.js
- lib/recurly/token.js
- packages/public-api-fixture-server/fixtures/tokens/proactive-token-test.json
- test/unit/recurly.test.js
- test/unit/risk.test.js
- test/unit/risk/three-d-secure.test.js
- test/unit/risk/three-d-secure/strategy/cybersource.test.js
- test/unit/risk/three-d-secure/strategy/worldpay.test.js
- types/lib/configure.d.ts
Introduces `Proactive 3DS`. 
This feature allows merchants to proactively start the 3DS flow for certain gateways (only `braintree` at the moment) before making a purchase and obtaining a `three_d_secure_action_required error`.
> Proactive 3DS changes

- .github/workflows/ci.yaml
- lib/recurly.js
- lib/recurly/element/card-cvv.js
- lib/recurly/elements.js
- lib/recurly/hosted-fields.js
- lib/recurly/token.js
- lib/recurly/validate.js
- packages/public-api-fixture-server/fixtures/field.html.ejs
- packages/public-api-fixture-server/views/e2e/hosted-fields-cvv.html.ejs
- test/e2e/display.test.js
- test/e2e/implementation.state.test.js
- test/e2e/recurly.test.js
- test/e2e/support/helpers.js
- test/unit/configure.test.js
- test/unit/elements.test.js
- test/unit/support/fixtures.js
- test/unit/token.test.js
- wdio.ci.conf.js
Allows `CardCvvElement` to tokenize the CVV by itself for use in CIT where the merchant wants the customer to confirm their CVV before checking out:
```js
const cvvElement = recurly.elements.CardCvvElement({});
cvvElement.attach(document.querySelector('#recurly-elements'));
```
> feat: Add support for tokenizing the CVV standalone

- lib/recurly/alternative-payment-methods/alternative-payment-methods.js
- lib/recurly/alternative-payment-methods/gateways/adyen.js
- types/lib/alternative-payment-methods.d.ts
Adds alternative path for setting customer fields such as billingAddress when initializing AlternativePaymentMethod class
> Allow billingAddress to be passed in via customer options on AlternativePaymentMethod

- lib/recurly/risk/three-d-secure/strategy/braintree.js
- test/unit/risk/three-d-secure/strategy/braintree.test.js
Send the new param, `currency`. in the Proactive Braintree Preflights flow.
> add currency to proactive preflights flow

- test/types/alternative-payment-methods.ts
- types/lib/alternative-payment-methods.d.ts
fixes #882
fixes #883
fixes #885
> chore: add missing type definitions for Adyen APM

- lib/recurly/risk/three-d-secure/strategy/stripe.js
- test/unit/risk/three-d-secure.test.js
- test/unit/risk/three-d-secure/strategy/stripe.test.js
For some payment methods handle their `PaymentIntent.next_action` by redirecting the user and then returning them to the checkout.
When this occurs, we shall require the three_d_secure_action_token_id be provided upon return, as follows:
```
const risk = recurly.Risk();
const threeDSecure = risk.ThreeDSecure({
actionTokenId: myActionTokenId
});
threeDSecure.on('token', function (token) {
// handle passing the action result
// token back to your server
// token.type => 'three_d_secure_action_result'
// token.id
// optionally, you may call threeDSecure.remove() to remove the element
});
threeDSecure.attach(document.querySelector('#my-auth-container'));
```
This change will handle re-submission of the action token, and determine if the Payment Intent has already been confirmed. If it is …
> Uses stripe.handleNextAction for payment intents

- README.md
- lib/recurly/paypal/strategy/complete.js
- test/types/paypal.ts
- test/unit/paypal/strategy/complete.test.js
- types/lib/paypal.d.ts
Allow users to set `config.gatewayCode` for paypal complete similar to paypal direct.
Sample usage 
```javascript
paypal = recurly.PayPal({
payPalComplete: true
});
paypalComplete.strategy.config.gatewayCode = 'wrfnlillojd9'
```
> Allow gateway code to set specific gateway for paypal complete

- README.md
- lib/recurly/paypal/strategy/complete.js
- test/types/paypal.ts
- test/unit/paypal/strategy/complete.test.js
- types/lib/paypal.d.ts
Reverts recurly/recurly-js#925
We originally merged rjs [924](https://github.com/recurly/recurly-js/pull/924) too early, but now it is ready for merge So we are reverting the revert of 924
> Revert "Revert "Allow gateway code to set specific gateway for paypal complete""

- test/e2e/recurly.test.js
- test/e2e/support/helpers.js
- I observed issues with input carriage in Safari, so this adds
an additional step in affected commands where the selenium driver
was ineffective with setValue
> Fixes Safari tests
