lib/recurly/pricing/calculations.js, test/server/fixtures/plans/tax_exempt.json, test/unit/pricing.test.js
Taxes are being added to tax exempt plans when the type is not usst. I think this should fix it but need to test. Any ideas?
Approvers: @chrissrogers
=> Fix tax exempt for non usst

test/unit/token.test.js
Hi there!
While I was working on something else with recurly.js, I found an improvement in test.
Looks like "when called with an HTMLFormElement" test creates a form with id="test-form", but the created form inputs have value 'undefined' IN STRING like so:
```html
...
<input type="text" data-recurly="cvv" value="undefined">
...
<input type="text" data-recurly="address1" value="undefined">    
<input type="text" data-recurly="address2" value="undefined">    
<input type="text" data-recurly="city" value="undefined"> 
....
```
This patch helps the form have correct intended values like so:
```html
...
<input type="text" data-recurly="cvv" value="">
...
<input type="text" data-recurly="address1" value="">    
<input type="text" data-recurly="address2" value="">    
<input type="text" …
```
=> Fixes a test form input values not to use string 'undefined'

lib/recurly.js, lib/recurly/bank-account.js, test/index.js, test/server/fixtures/token/index.js, test/unit/bank-account.test.js
- adds bankAccount class 
- includes `token` function for getting tokens with bank account info for ach payments
- includes `bankInfo` function for getting bank info (name) using a routing number
=> Add support for ach payments with bank accounts

LICENSE.md, bower.json, component.json
- See #182
- Also updates date in license
=> Removes bower.json and updates Component metadata

lib/recurly/bank-account.js, lib/recurly/pricing/index.js, lib/recurly/token.js, lib/util/normalize.js
- To make [code climate happy](https://codeclimate.com/github/recurly/recurly-js/lib/recurly/token.js)
- Extracts normalizer into separate module
- Removes unnecessary routines
- Cleans up some syntax
=> Cleans up token, bankAccount, and pricing modules

.jshintrc, lib/errors.js, lib/recurly.js, lib/recurly/bank-account.js, lib/recurly/coupon.js, lib/recurly/open.js, lib/recurly/paypal.js, lib/recurly/plan.js, lib/recurly/pricing/attach.js, lib/recurly/pricing/calculations.js, lib/recurly/pricing/promise.js, lib/recurly/relay.js, lib/recurly/tax.js, lib/recurly/token.js, lib/recurly/validate.js, lib/util/dom.js
- Part of an effort to make code climate more useful
- Follow-up to #208
- This also adds a return to `dom.data` on both get and set calling patterns. This is simply a util API change and has no impact on the library functionality as a whole. I would still like to assess separately whether to adopt an external dom library or to pull our dom utils out into a separate lib.
=> Adds .jshintrc and corrects for JSHint

lib/recurly.js
=> Adds better documentation for recurly.configure

lib/recurly.js
- Prevents collision with libraries using the default prefix
- See duojs/test#69
- Includes #207
=> Adds prefix to jsonp callbacks

CHANGELOG.md, component.json, lib/version.js, package.json
Updates for version 3.1.1 release.
cc: @chrissrogers
=> Version 3.1.1

.travis.yml, README.md, karma.conf.js, package.json
Adds CI testing for the following platforms
- Latest Chrome
- Latest Firefox
- Latest Safari
- Latest Opera
- IE 10
- IE 11
- iOS 8.4 - 9.2
- Android 5.1
=> Adds sauce support

.travis.yml, Makefile, karma.conf.js, karma.sauce.conf.js, test/token.test.js
- Adds tests around #231 
- Splits sauce tests into their own make task
=> Required field tests

lib/recurly/pricing/index.js
- This [increases our code quality](https://codeclimate.com/github/recurly/recurly-js/compare/pricing-simplicity) a bit.
=> Simplifies pricing updaters

lib/recurly/bus.js, lib/recurly/message.js, package.json
- From 6.0.0 to 7.1.1
- https://github.com/then/promise/compare/6.0.0...7.1.1
- Updates some documentation
Signed-off-by: Christopher Rogers <chrissrogers@gmail.com>
=> Updates then/promise library

lib/recurly/validate.js, test/validate.test.js
- To be made available Oct 2016
=> Adds detection of new Mastercard BIN ranges

lib/recurly/pricing/calculations.js, test/pricing.test.js, test/server/fixtures/plans/basic/coupons/coop-trial-ext.json, test/server/fixtures/plans/basic/index.json, test/server/fixtures/plans/intermediate/coupons/coop-trial-ext.json
- Trial extension coupons will impose the effect of a trial on subscriptions whether or not their plan has a trial
=> Adds pricing case for trial extension coupons

CHANGELOG.md, lib/version.js, package.json
=> Version 4.0.2

CHANGELOG.md, lib/version.js, package.json
- Updates discount type indication #250
=> Version 4.0.3

CHANGELOG.md, lib/version.js, package.json
* adds functionality for running fraud data collector #254
=> Version 4.0.4

.travis.yml
=> Sets Travis node version to latest stable

lib/recurly/fraud.js, test/server/fixtures/fraud_data_collector.json, test/server/index.js, test/support/fixtures.js, test/token.test.js
- Adds API fixtures
- Adds bus spy tests
=> Bolsters tokenization fraud detection tests

.travis.yml, Makefile, karma.ci.conf.js, package.json
- 💇 
- runs slightly faster
- better test isolation, so that a failure in one browser env doesn't require a rerun of all
- artifacts now require passage of phantom tests and not all
=> Parallelizes travis tests

lib/errors.js, lib/recurly.js, lib/recurly/giftcard.js, lib/recurly/pricing/attachment.js, lib/recurly/pricing/calculations.js, lib/recurly/pricing/index.js, lib/recurly/pricing/promise.js, lib/recurly/tax.js, test/giftcard.test.js, test/pricing/attachment.test.js, test/pricing/pricing.test.js, test/server/fixtures/gift_cards/australianCard.json, test/server/fixtures/gift_cards/hundredDollarCard.json, test/server/fixtures/gift_cards/invalidCard.json, test/server/fixtures/gift_cards/superGiftcardForMe.json, test/server/index.js, test/support/fixtures.js
example:
`pricing.plan("basic",{quantity:1}).address({ country: "US", state: "CO" }).giftcard("4EAF9LSOMEHASHSORTOFTHING").tax().done();`
=> Add giftcard support.

lib/recurly.js, test/configure.test.js
- options.fields was not properly initialized when only options.style.all was set
=> Fixes issue with config coercion

lib/recurly/pricing/attachment.js, test/pricing/attachment.test.js, test/support/fixtures.js
- When a form has only a billing address, fixes an issue where shipping address would be set as blank and override billing taxes
=> Fixes issue with address attachment

lib/recurly/hosted-field.js, lib/recurly/hosted-fields.js, package.json
Reverts recurly/recurly-js#293
=> Revert "Add support for tabbing in a Mobile browser."

test/unit/validate.test.js
Attempting to get the v3 build to complete.
=> fix test that is now failing because expiry isn’t a future date anymore

CHANGELOG.md, lib/recurly/apple-pay.js, lib/version.js, package.json, test/apple-pay.test.js, test/token.test.js
This will allow RJS to also pull out info from address and name fields to add to token.
=> Update Apple Pay init to receive payment form

index.js, lib/recurly/bank-account.js, lib/recurly/coupon.js, lib/recurly/giftcard.js, lib/recurly/open.js, lib/recurly/paypal.js, lib/recurly/plan.js, lib/recurly/relay.js, lib/recurly/tax.js, lib/recurly/token.js, lib/util/normalize.js
- Those starting with `/*!` are preserved by webpack during minification, so this will reduce minified distribution size
- Some of these comments were just too obvious
=> Removes some superfluous comments

lib/recurly.js, lib/recurly/hosted-field.js, lib/recurly/hosted-fields.js
- Sends version to hosted instances via hosted fields
=> Adds parentVersion property

lib/recurly.js, lib/recurly/relay.js
Checks origin before accepting messages
=> Patch for issue #329

lib/recurly/relay.js
- simple refactor of relay origin detection
=> Prevents relay from polluting main Recurly instance

lib/recurly/relay.js
Builds on #340 and supercedes #339
=> Makes origin checking compatible with IE11 + possibly others

lib/recurly/paypal/braintree.js
- If a device fingerprint can be obtained, attach it to PayPal tokenization requests
=> Sends Braintree device fingerprint along with PayPal requests

lib/recurly.js, lib/recurly/bus.js, lib/recurly/relay.js, lib/recurly/token.js, lib/recurly/validate.js, lib/util/normalize.js, package.json
- Removes several shim dependencies no longer needed
- 120k -> 113k  (minified)
=> Removes old dependencies

Makefile
- Allows developers to assign their own cert
=> Adds support for local certificate assignment

package.json, webpack.config.js
- Ensures support for IE 10, IE 11
- Fixes #350
=> Adds polyfill for Object.assign

package-lock.json
=> Adds package-lock.json

lib/recurly/bus.js, lib/recurly/frame.js
- Errors in event listeners would bubble up to this try-catch
=> Fixes error handler within bus relay handler

lib/recurly/apple-pay.js
=> Adds company attribute collection to ApplePay tokenizer

lib/recurly.js, lib/recurly/fraud.js, lib/recurly/token.js
- Allows a merchant to pass Braintree fraud data collection data into credit card tokenization requests.
=> Adds support for Braintree deviceData

lib/recurly/paypal/strategy/direct.js, test/paypal/strategy/direct.test.js
- Adds it to the payload if we have one
=> Passes PayPal amount param to API start endpoint

lib/recurly.js, lib/recurly/apple-pay.js, lib/recurly/token.js
- If an ApplePay instance was given a Pricing instance, it would not always update its price values on init.
=> Fixes Apple Pay pricing initialization

lib/recurly.js, lib/recurly/hosted-fields.js
- Hosted fields would not receive configuration updates
- Regression caused by #303
- Fixes #376
=> Fixes field style propagation

lib/recurly/pricing/attachment.js, lib/recurly/pricing/index.js
- Fires when the Attachment class has finalized
- Fixes #270
=> Adds ‘attached’ event to Pricing

lib/recurly/hosted-fields.js
- Supports upcoming dropdown for mobile
=> Adds inputType configuration to HostedField.fieldConfig

.travis.yml, karma.ci.conf.js, test/token.test.js
- More iOS and Android for poor Travis and Sauce
=> Updates Sauce mobile testing environments

README.md
=> Updates README build status display

package-lock.json, package.json
- Pins `karma-sauce-launcher@1.1.0` in `package.json` to maintain sauce functionality
- **Follow-up**: fix sauce behavior for `karma-sauce-launcher@1.2.0` -- review configuration and sauce calls
=> Updates package-lock.json

karma.conf.js, lib/errors.js, lib/recurly.js, lib/recurly/apple-pay.js, lib/recurly/paypal/strategy/index.js, lib/recurly/pricing/checkout/attachment.js, lib/recurly/pricing/checkout/calculations.js, lib/recurly/pricing/checkout/index.js, lib/recurly/pricing/index.js, lib/recurly/pricing/promise.js, lib/recurly/pricing/subscription/attachment.js, lib/recurly/pricing/subscription/calculations.js, lib/recurly/pricing/subscription/embedded.js, lib/recurly/pricing/subscription/index.js, lib/recurly/tax.js, lib/util/decimalize-member.js, lib/util/decimalize.js, package-lock.json, package.json, test/apple-pay.test.js, test/paypal/strategy/strategy.test.js, test/pricing/checkout/checkout.test.js, test/pricing/subscription/embedded.test.js, test/recurly.test.js, test/server/fixtures/plans/basic-gbp.json, test/server/fixtures/tax/index.js
- **To follow #394** - includes `SubscriptionPricing` Apple Pay and PayPal adaptations
- Adds `CheckoutPricing/Attachment` class and `CheckoutPricing.attach` factory
- Adds `CheckoutPricing.shippingAddress` setter
- Updates `CheckoutPricing/Calculations` to prefer shipping address to (billing) address when obtaining tax rates.
- Allows `CheckoutPricing.adjustment` to update existing adjustments in-place, matched by their `code`
```html
<section id="checkout">
Subscription 1
<select data-recurly="plan" data-recurly-subscription="0">
<option value="basic">Basic</option>
<option value="notbasic">Not Basic</option>
</select>
Subscription 1 Add-ons
<span data-recurly="addon_price" data-recurly-subscription="0" data-recurly-addon="my_addon_code_1"></span>
<input type="text" data-recurly="addon" …
```
=> CheckoutPricing: Attachment and Shipping Addresses

lib/recurly/pricing/checkout/attachment.js
- Fixes CheckoutPricing re-attachment
=> Fixes issue with detachment reference to observer

lib/recurly/pricing/checkout/attachment.js, lib/util/flatten.js
- Discovery would fail if there were no plan elements
=> Fixes CheckoutPricing attachment orphaned element discovery

lib/recurly/pricing/checkout/index.js, test/pricing/checkout/checkout.test.js
Signed-off-by: Christopher Rogers <chrissrogers@gmail.com>
=> Ensures an invalid coupon emits an error on CheckoutPricing

lib/recurly/pricing/checkout/calculations.js, lib/recurly/pricing/subscription/calculations.js, lib/recurly/pricing/subscription/embedded.js, lib/recurly/pricing/subscription/index.js, test/pricing/checkout/checkout.test.js
- taxes must be applied to item subtotals less their discount
=> Fixes CheckoutPricing discount taxation

lib/recurly/pricing/checkout/calculations.js
- Credits (negative adjustments) do not decrease taxation
=> Fixes taxation of credit adjustments

lib/recurly/pricing/checkout/calculations.js
- Subtotal compares must be parsed before comparison
=> Fixes subscription sort for discount selection

lib/recurly.js, lib/recurly/hosted-field.js, lib/recurly/hosted-fields.js
- Adds `recurly-hosted-field-valid` css class
- Adds `recurly-hosted-field-invalid` css class
- Adds `recurly-hosted-field-[type]-valid` css class
- Adds `recurly-hosted-field-[type]-invalid` css class
- Adapts hosted field config validation to support a single card hosted field
=> Adds Card Hosted Field support

lib/recurly/pricing/checkout/calculations.js, test/pricing/checkout/checkout.test.js
- Ensures coupon discount amount calculations have the proper type before performing fixed amount discount calculations
=> Adds safety check to calculation of discount amount

karma.conf.js, lib/recurly.js, lib/recurly/hosted-field.js, lib/recurly/hosted-fields.js, lib/util/dom.js, package-lock.json, package.json, test/hosted-field.test.js, test/hosted-fields.test.js, test/server/fixtures/field.html.ejs
- These changes will allow customers to use the tab buttons in Safari on iOS to tab from form inputs to Recurly-js hosted field inputs
=> Mobile Tabbing for Recurly.js

lib/recurly/paypal/strategy/direct.js, lib/recurly/paypal/strategy/index.js
- Only supported by the DirectStrategy
=> Adds support for logo assignment in PayPal flow

CHANGELOG.md, karma.conf.js, lib/recurly.js, lib/recurly/hosted-field.js, lib/recurly/hosted-fields.js, lib/util/dom.js, package-lock.json, package.json, test/hosted-field.test.js, test/hosted-fields.test.js, test/server/fixtures/field.html.ejs
- These changes will allow customers to use the tab buttons in Safari on iOS to tab from form inputs to Recurly-js hosted field inputs. Note that the hosted field inputs may be multiple inputs per field or a single combined field.
=> Mobile Tabbing for multiple/combined card fields

lib/recurly/event.js, lib/recurly/request.js, lib/recurly/worker.js, test/request.test.js, test/worker.test.js
- Built atop #463 
- Adds IntervalWorker
- Updates EventDispatcher to use a worker to dispatch events in ten second intervals
- Updates Request to accept empty responses
=> Batched reporting

lib/recurly/fraud.js
- Fixes #469
- Form detection had assumed presence of the number field. This opens form detection to all hosted field types
=> Fixes Kount fraud detection when using Card field

lib/recurly.js, lib/recurly/event.js
- Built atop #464 
- Dispatches events when a hosted field is focused or blurred
=> Hosted field reporting

lib/recurly.js, lib/recurly/event.js, lib/recurly/pricing/checkout/index.js, lib/recurly/pricing/index.js, lib/recurly/pricing/subscription/embedded.js, lib/recurly/pricing/subscription/index.js
- Built atop #465 
- Dispatches events when pricing changes occur
=> Pricing reporting

test/server/fixtures/field.html.ejs, test/token.test.js, test/validate.test.js
- Intended to increase coverage as per https://coveralls.io/builds/19331116/source?filename=lib%2Frecurly%2Ftoken.js
=> Adds in-field tokenization test scenario

package-lock.json
- https://nodesecurity.io/advisories/720
=> Updates Cryptiles dependency

.travis.yml, karma.ci.conf.js, package.json
User basis has shifted, thus we should shift our testing platforms accordingly.
=> Updates browser platforms in CI

lib/recurly/pricing/subscription/attachment.js
#471 was missing a reference to our polyfill Promise library, which will make IE11 happy
=> Fixes reference to Promise library

lib/recurly.js
- Simple addition to event reporting
=> Adds field type to reporter events on field focus and blur

webpack.config.js
- More reliable hostname determination in development
=> Updates dev hostname to js.lvh.me

lib/recurly/errors.js
=> Adds adyen-error

lib/recurly.js, lib/recurly/bank-account.js, lib/recurly/token.js, lib/recurly/validate.js, test/bank-account.test.js, test/server/fixtures/token/index.js, test/token.test.js, test/validate.test.js
- Moves validations from token modules to validate module
- Formats validation errors in a way that associates field names with error messages
=> Adds 'details' to token validation errors

lib/recurly/apple-pay.js, test/apple-pay.test.js
=> Corrects ApplePay completeShippingMethodSelection call signature

lib/recurly/risk/risk.js, lib/recurly/risk/three-d-secure/strategy/adyen.js, lib/recurly/risk/three-d-secure/strategy/strategy.js, lib/recurly/risk/three-d-secure/strategy/stripe.js, lib/recurly/risk/three-d-secure/strategy/test.js, lib/recurly/risk/three-d-secure/strategy/wirecard.js, lib/recurly/risk/three-d-secure/three-d-secure.js, package-lock.json, test/risk.test.js, test/risk/three-d-secure.test.js, test/risk/three-d-secure/strategy.test.js, test/risk/three-d-secure/strategy/adyen.test.js, test/risk/three-d-secure/strategy/stripe.test.js, test/risk/three-d-secure/strategy/test.test.js, test/risk/three-d-secure/strategy/wirecard.test.js, test/server/fixtures/three_d_secure/start.json, test/server/fixtures/tokens/action-token-adyen-3ds1.json, test/server/fixtures/tokens/action-token-adyen-fingerprint.json, test/server/fixtures/tokens/action-token-adyen.json, test/server/fixtures/tokens/action-token-stripe.json, test/server/fixtures/tokens/action-token-test.json, test/server/fixtures/tokens/action-token-wirecard.json
- Adds `AdyenStrategy` test suite
- Updates `ThreeDSecure` strategy discovery to detect based on strategy name assigned on strategy class
- Restructures 3DSAT fixtures
- Updates `Risk.browserInfo` keys for direct API compatibility
=> Adds Wirecard 3D Secure support

lib/recurly/risk/three-d-secure/three-d-secure.js, test/risk.test.js, test/risk/three-d-secure.test.js, test/risk/three-d-secure/strategy/adyen.test.js, test/risk/three-d-secure/strategy/stripe.test.js, test/risk/three-d-secure/strategy/wirecard.test.js
=> Requires actionTokenId to be provided when instantiating ThreeDSecure

lib/recurly/risk/three-d-secure/strategy/strategy.js, test/risk/three-d-secure/strategy.test.js
=> Sets ThreeDSecureStrategy#container height and width to 100%

lib/recurly.js, lib/recurly/fraud.js
Resolving https://github.com/recurly/recurly-js/issues/545
=> adds error emission instead of throwing in Fraud

karma.conf.js, lib/recurly/bus.js, lib/recurly/errors.js, lib/recurly/risk/risk.js, lib/recurly/risk/three-d-secure/index.js, lib/recurly/risk/three-d-secure/strategy/strategy.js, lib/recurly/risk/three-d-secure/strategy/worldpay.js, lib/recurly/risk/three-d-secure/three-d-secure.js, lib/recurly/token.js, test/risk.test.js, test/risk/three-d-secure.test.js, test/risk/three-d-secure/strategy/worldpay.test.js, test/server/fixtures/risk/preflights.js, test/server/fixtures/tokens/action-token-worldpay.json, test/server/fixtures/tokens/index.js, test/server/index.js, test/util/group-by.test.js
- Strategy and preflight request modifications to facilitate Worldpay 3D Secure tokenization
=> Adds 3D Secure support for Worldpay

.eslintrc.js, Makefile, lib/recurly/errors.js, lib/recurly/frame.js, lib/recurly/paypal/strategy/direct.js, lib/recurly/paypal/strategy/index.js, lib/recurly/validate.js
=> Updates eslint config to avoid escaping quotes in strings

.travis.yml
- Adds async pipe modification
- Updates node runtime
=> Improves Travis CI stability

.github/ISSUE_TEMPLATES/01_bug_report.md, .github/ISSUE_TEMPLATES/02_question_or_feature_request.md
=> Adds issue templates

karma.ci.conf.js
- Improves connection reliability to Browserstack
=> Forces Browserstack local connection and identifier in Karma CI test runs

lib/recurly/validate.js, lib/util/deep-assign.js, test/unit/validate.test.js
Adds union pay as a card type.
=> Adds union pay

lib/recurly/plan.js
Reduces the number of outbound requests for plans.
=> Caches plan requests

lib/recurly/element/element.js, lib/util/normalize.js, test/unit/element.test.js
The term "whitelist" is not very inclusive. "Allowlist" is better for Recurly's culture of diversity and inclusion.
=> Use more inclusive terms

index.js, webpack.config.js
- Adds attribution url to source
- Adds attribution to distributable
=> Adds open source attribution comment

test/types/elements.ts, types/lib/elements.d.ts
Also updates Element test to include `.configure` and `.remove` and corrects return types for IndividualElement methods.
=> Adds Element.focus method to types

lib/recurly.js, lib/recurly/errors.js, lib/recurly/reporter.js, lib/recurly/request.js
=> Fixes error reporting

.travis.yml
Follow-up to #645 which was mis-configured
=> Fixes recurly.css artifact extraction and disables react-recurly tests for pull request builds

test/types/recurly-error.ts, types/lib/error.d.ts
**Description**:
Add `fields` and `details` types to **RecurlyError** defintion.
**Impact**:
Low
**Testing**:
Unit tests
=> Add fields and details types to RecurlyError

webpack.config.js
No need to specify the hostname here.
=> Removes specification of development server host name

lib/recurly/validate.js, test/unit/validate.test.js
Adds support for card type Tarjeta Naranja.
=> Add BIN range for Tarjeta Naranja

lib/recurly.js, test/e2e/display.test.js, test/e2e/support/helpers.js, test/unit/recurly.test.js
Configure the library at runtime to point to the EU or US endpoint.
=> Adding the eu api url for eu on rjs

.eslintrc.js, lib/recurly/apple-pay/apple-pay.braintree.js, lib/recurly/apple-pay/apple-pay.js, lib/recurly/apple-pay/index.js, test/server/fixtures/apple_pay/token.js, test/unit/apple-pay.test.js, types/lib/apple-pay.d.ts
Support **ApplePay** through **Braintree**.
=> ApplePay through Braintree

lib/recurly/apple-pay/apple-pay.js, test/unit/apple-pay.test.js
Accept ApplePay data together non-address fields inputs.
=> ApplePay tokenize tax fields

lib/recurly/risk/three-d-secure/strategy/adyen.js, test/unit/risk/three-d-secure/strategy/adyen.test.js
Update 3ds frame to include default event name
=> Adyen 3ds risk strategy frame update

lib/recurly/elements.js
Allows RJS to have the cardElement work with the cardBrandElement
=> Rjs brand picker

test/types/3d-secure.ts, test/types/adyen.ts, test/types/apple-pay.ts, test/types/bank-account.ts, test/types/configure.ts, test/types/elements.ts, test/types/gift-card.ts, test/types/index.d.ts, test/types/paypal.ts, test/types/token/elements.ts, test/types/token/hosted-field.ts, test/types/validate.ts
Updating comments to match [what was updated in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60697)
This is causing test failures in our [automated pull requests](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62361)
=> Replace $ExpectError with @ts-expect-error

lib/recurly.js, lib/recurly/alternative-payment-methods/alternative-payment-methods.js, lib/recurly/alternative-payment-methods/gateways/adyen.js, lib/recurly/alternative-payment-methods/gateways/base.js, lib/recurly/alternative-payment-methods/index.js, lib/recurly/errors.js, lib/util/dom.js, test/unit/alternative-payment-methods/alternative-payment-methods.test.js, types/lib/alternative-payment-methods.d.ts, types/lib/recurly.d.ts
Support Payment Methods with Adyen.
=> Adyen Payment Endpoints

types/lib/recurly.d.ts
=> fix(types): add type definition for Recurly#ready

types/lib/paypal.d.ts
=> chore(paypal): add types for display options

lib/recurly/request.js, test/server/index.js, test/unit/adyen.test.js, test/unit/alternative-payment-methods/alternative-payment-methods.test.js, test/unit/apple-pay.test.js, test/unit/bank-account.test.js, test/unit/coupon.test.js, test/unit/gift-card.test.js, test/unit/google-pay/google-pay.test.js, test/unit/item.test.js, test/unit/paypal/paypal.test.js, test/unit/paypal/strategy/braintree.test.js, test/unit/paypal/strategy/strategy.test.js, test/unit/plan.test.js, test/unit/request.test.js, test/unit/risk/three-d-secure/strategy/cybersource.test.js, test/unit/support/helpers.js, test/unit/tax.test.js, test/unit/token.test.js, test/unit/venmo/strategy/braintree.test.js, test/unit/venmo/venmo.test.js
- Reduces test duplication on the order of 30% of overall test count
- Removes broad jsonp request testing across entity tests
- Adds tests specific to the Request.jsonp implementation
=> Focuses scope of jsonp tests

Makefile, webpack.config.js
Fixes the dev server for the new version of webpack
=> fix(dev server): Updates for webpack version bump

.github/workflows/ci.yaml
Change Artifact Upload Path to match the one used before
=> Change Artifact Upload Path

.github/workflows/ci.yaml, karma.ci.conf.js, package-lock.json, wdio.ci.conf.js, webpack.test.config.js
- Should prevent push runs on pull requests
- fixes coverage reports in CI
=> Adds GHA concurrency on PR group

.github/workflows/ci.yaml
- Consolidates pull request verification to a CI step
=> Adds verify step

lib/recurly/paypal/index.js, lib/recurly/paypal/strategy/complete.js, test/unit/paypal/paypal.test.js, test/unit/paypal/strategy/complete.test.js
PayPal Complete using PayPal Method
=> PayPal Complete using PayPal Method

lib/recurly/risk/three-d-secure/strategy/paypal-complete.js, lib/recurly/risk/three-d-secure/three-d-secure.js, packages/public-api-fixture-server/fixtures/tokens/action-token-paypal-complete.json, test/unit/risk/three-d-secure/strategy/paypal-complete.test.js
Add support for 3D Secure Authentication using PayPal Complete payment gateway
=> PayPal Complete 3DS

lib/recurly.js, lib/recurly/fraud.js, packages/public-api-fixture-server/fixtures/risk/info.js, test/unit/fraud.test.js
=> Add PayPal Fraudnet Script

Dockerfile, Makefile, docker-compose.yml, karma.conf.js, test/e2e/display.test.js, test/e2e/support/helpers.js, wdio.conf.js, webpack.config.js
```
docker compose run recurly-js make test-unit
```
=> Fixes Chrome execution within container

lib/recurly/alternative-payment-methods/gateways/adyen.js, test/unit/alternative-payment-methods/alternative-payment-methods.test.js
Add Support for Sofort on Adyen Components
- Return Adyen checkout state for active payment method even for payment methods that does not have an internal state
=> Add Support for Sofort on Adyen Components

lib/recurly/venmo/strategy/braintree.js
=> Expose Venmo Device Data

lib/recurly/alternative-payment-methods/alternative-payment-methods.js, lib/recurly/alternative-payment-methods/gateways/adyen.js, test/unit/alternative-payment-methods/alternative-payment-methods.test.js
Add support for Cash App via Adyen to Alternative Payment Methods
=> Support Cash App

.eslintrc.js, .github/workflows/publish-types.yaml, package-lock.json, package.json, test/types/apple-pay.ts, test/types/google-pay.ts, types/lib/apple-pay/index.d.ts, types/lib/google-pay/index.d.ts
Fixes the generation of [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) types.
Manually generated a [pull request to DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69977) using these changes
=> Fixing types generation

lib/recurly/venmo/strategy/braintree.js, lib/recurly/venmo/strategy/index.js
Updates some development debug code and a comment.
=> Small venmo tweaks for development debugging

lib/recurly/risk/risk.js, lib/recurly/risk/three-d-secure/strategy/braintree.js, lib/recurly/risk/three-d-secure/three-d-secure.js, lib/recurly/token.js, test/unit/risk/three-d-secure/strategy/braintree.test.js
Passes billing address fields submitted via `data-recurly` attributes to Proactive 3DS flow.
=> Pass billingAddress fields for Proactive 3DS

lib/recurly/amazon/amazon-pay.js, lib/recurly/token.js
Adds multi currency support for Amazon UK and EU
=> Add multi currency support for Amazon UK and EU

README.md, lib/recurly/paypal/strategy/complete.js, test/types/paypal.ts, test/unit/paypal/strategy/complete.test.js, types/lib/paypal.d.ts
Reverts recurly/recurly-js#924 
No changes intended here, just resetting `master`
=> Revert "Allow gateway code to set specific gateway for paypal complete"

lib/recurly.js, lib/recurly/element/element.js, lib/recurly/risk/three-d-secure/three-d-secure.js, lib/util/one-in.js, lib/util/web-storage.js, test/conf/browserstack.js, test/unit/recurly.test.js, test/unit/util/one-in.test.js, test/unit/util/web-storage.test.js
1 in 1,000 sessions to request a canary Elements instance
=> Adds Elements canary

package-lock.json, packages/public-api-fixture-server/index.js
- The mobile e2e tests rely on an API proxy to meet sandboxing requirements
- This proxy needed to be updated to match new resource layouts
- Bumps various testing packages within their major version
=> Fixes mobile e2e API proxy
